name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 4.0x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: msbuild /p:Configuration=Release Terminalix.sln
    - name: Test
      run: dotnet test --no-build --verbosity normal
